In [20]:
import pandas as pd

In [21]:
df = pd.read_csv("./Study3.csv")
df.columns.values

array(['PID', 'q1', 'q1ans', 'q2', 'q2ans', 'q3', 'q3ans', 'q4', 'q4ans',
       'q5', 'q5ans', 'q6', 'q6ans', 'q7', 'q7ans', 'q8', 'q8ans', 'q9',
       'q9ans', 'q10', 'q10ans', 'q11', 'q11ans', 'q12', 'q12ans', 'q13',
       'q13ans', 'q14', 'q14ans', 'q15', 'q15ans', 'q16', 'q16ans', 'q17',
       'q17ans', 'q18', 'q18ans', 'q19', 'q19ans', 'q20', 'q20ans', 'q21',
       'q21ans', 'q22', 'q22ans', 'q23', 'q23ans', 'q24', 'q24ans', 'q25',
       'q25ans', 'deckA_effort', 'deckA_boredom', 'deckB_effort',
       'deckB_boredom', 'selfadmit', 'attencheck', 'nfc_1r', 'nfc_2r',
       'nfc_3r', 'nfc_4r', 'nfc_5r', 'nfc_6r', 'nfc_7r', 'nfc_8r',
       'nfc_9r', 'nfc_10r', 'nfc_11r', 'nfc_12r', 'nfc_13r', 'nfc_14r',
       'nfc_15r', 'nfc_16r', 'nfc_17r', 'nfc_18r', 'bps1', 'bps2', 'bps3',
       'bps4', 'bps5', 'bps6', 'bps7', 'bps8'], dtype=object)

In [22]:
df

,PID,q1,q1ans,q2,q2ans,q3,q3ans,q4,q4ans,q5,...,nfc_17r,nfc_18r,bps1,bps2,bps3,bps4,bps5,bps6,bps7,bps8
0,1,DECK B,incorrect,DECK A,,DECK A,,DECK B,incorrect,DECK B,...,2,2,3,3,3,4,3,3,1,1
1,2,DECK A,,DECK A,,DECK B,incorrect,DECK A,,DECK A,...,2,5,5,3,2,2,5,5,5,5
2,3,DECK B,blank,DECK B,correct,DECK B,correct,DECK A,,DECK A,...,3,4,2,3,2,3,3,3,3,3
3,4,DECK A,,DECK A,,DECK B,correct,DECK B,correct,DECK B,...,3,4,6,2,5,5,2,2,4,3
4,5,DECK A,,DECK A,,DECK A,,DECK B,incorrect,DECK B,...,3,2,7,4,7,5,3,5,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,187,DECK B,incorrect,DECK A,,DECK A,,DECK A,,DECK A,...,4,4,4,4,6,4,6,4,5,5
174,188,DECK A,,DECK A,,DECK B,correct,DECK A,,DECK A,...,3,3,4,4,4,5,2,2,4,4
175,190,DECK B,correct,DECK B,correct,DECK B,correct,DECK A,,DECK A,...,4,5,5,2,6,4,7,5,5,5
176,191,DECK A,,DECK B,incorrect,DECK A,,DECK A,,DECK B,...,3,4,6,6,5,6,5,2,2,4
177,192,DECK A,,DECK A,,DECK A,,DECK A,,DECK B,...,2,4,5,5,6,4,5,5,6,5

In [23]:
df.drop(["deckA_effort", "deckA_boredom", "deckB_effort", "deckB_boredom"], axis=1, inplace=True)

In [24]:
df.drop(["bps1", "bps2", "bps3", "bps4", "bps5", "bps6", "bps7", "bps8"], axis=1, inplace=True)

In [25]:
df.columns.values

array(['PID', 'q1', 'q1ans', 'q2', 'q2ans', 'q3', 'q3ans', 'q4', 'q4ans',
       'q5', 'q5ans', 'q6', 'q6ans', 'q7', 'q7ans', 'q8', 'q8ans', 'q9',
       'q9ans', 'q10', 'q10ans', 'q11', 'q11ans', 'q12', 'q12ans', 'q13',
       'q13ans', 'q14', 'q14ans', 'q15', 'q15ans', 'q16', 'q16ans', 'q17',
       'q17ans', 'q18', 'q18ans', 'q19', 'q19ans', 'q20', 'q20ans', 'q21',
       'q21ans', 'q22', 'q22ans', 'q23', 'q23ans', 'q24', 'q24ans', 'q25',
       'q25ans', 'selfadmit', 'attencheck', 'nfc_1r', 'nfc_2r', 'nfc_3r',
       'nfc_4r', 'nfc_5r', 'nfc_6r', 'nfc_7r', 'nfc_8r', 'nfc_9r',
       'nfc_10r', 'nfc_11r', 'nfc_12r', 'nfc_13r', 'nfc_14r', 'nfc_15r',
       'nfc_16r', 'nfc_17r', 'nfc_18r'], dtype=object)

In [26]:
df["attencheck"].value_counts()

attencheck
Blue     164
Green     14
Name: count, dtype: int64

In [27]:
df = df.drop(df[df["attencheck"] == "Green"].index)

In [28]:
df["attencheck"].value_counts()

attencheck
Blue    164
Name: count, dtype: int64

In [29]:
df["selfadmit"].value_counts()

selfadmit
No     136
Yes     28
Name: count, dtype: int64

In [30]:
df = df.drop(df[df["selfadmit"] == "Yes"].index)

In [31]:
df["selfadmit"].value_counts()

selfadmit
No    136
Name: count, dtype: int64

In [32]:
df

,PID,q1,q1ans,q2,q2ans,q3,q3ans,q4,q4ans,q5,...,nfc_9r,nfc_10r,nfc_11r,nfc_12r,nfc_13r,nfc_14r,nfc_15r,nfc_16r,nfc_17r,nfc_18r
0,1,DECK B,incorrect,DECK A,,DECK A,,DECK B,incorrect,DECK B,...,3,3,3,3,4,3,3,2,2,2
1,2,DECK A,,DECK A,,DECK B,incorrect,DECK A,,DECK A,...,3,3,3,4,2,3,3,4,2,5
2,3,DECK B,blank,DECK B,correct,DECK B,correct,DECK A,,DECK A,...,2,3,4,2,4,4,3,4,3,4
4,5,DECK A,,DECK A,,DECK A,,DECK B,incorrect,DECK B,...,4,4,4,4,2,4,3,4,3,2
5,6,DECK B,incorrect,DECK B,correct,DECK B,correct,DECK A,,DECK A,...,2,3,4,2,3,4,4,3,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,187,DECK B,incorrect,DECK A,,DECK A,,DECK A,,DECK A,...,4,4,4,4,4,4,4,4,4,4
174,188,DECK A,,DECK A,,DECK B,correct,DECK A,,DECK A,...,3,3,3,3,3,3,3,3,3,3
175,190,DECK B,correct,DECK B,correct,DECK B,correct,DECK A,,DECK A,...,4,4,5,2,4,3,2,5,4,5
176,191,DECK A,,DECK B,incorrect,DECK A,,DECK A,,DECK B,...,4,3,2,3,4,4,4,5,3,4
177,192,DECK A,,DECK A,,DECK A,,DECK A,,DECK B,...,4,3,1,2,2,4,2,4,2,4