In [16]:
import pandas as pd

In [17]:
df = pd.read_csv("./Study9.csv")

In [18]:
df

,PID,attencheck1,q1,@1_str1,@2_str1,@3_str1,@4_str1,@5_str1,@6_str1,@7_str1,...,moe_9,moe_10,moe_11,moe_12,moe_13,moe_14,moe_15,moe_16,moe_17,moe_18
0,1,Green,DECK A,,,,,,,,...,5,5,4,3,5,4,3,4,4,3
1,2,Green,DECK B,blue,,,,,,green,...,4,3,4,3,1,4,3,4,1,1
2,3,Green,DECK B,,,red,yellow,,,,...,5,4,3,4,3,4,4,4,3,3
3,4,Green,DECK A,,,,,,,,...,4,3,5,1,1,5,4,3,4,3
4,5,Green,DECK A,,,,,,,,...,4,3,3,3,1,4,3,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,187,Green,DECK B,,,,,,,green,...,4,5,4,5,4,5,4,5,4,5
187,188,Green,DECK B,,,,,,blue,,...,4,5,3,4,5,5,3,3,4,5
188,189,Green,DECK B,,,,,,blue,green,...,4,5,4,5,4,5,4,5,4,5
189,190,Green,DECK B,,,red,,blue,,,...,4,5,4,5,4,5,4,5,4,4
190,191,Green,DECK B,,,,yellow,,,,...,5,4,5,4,5,4,4,4,4,4

In [19]:
df.columns.values

array(['PID', 'attencheck1', 'q1', ..., 'moe_16', 'moe_17', 'moe_18'],
      dtype=object)

## FÃ¥r kolla i datasetet ist

In [20]:
df.drop(["first_deckA_mental", "first_deckA_boredom", "first_deckB_mental", "first_deckB_boredom",
         "second_deckA_mental", "second_deckA_boredom", "second_deckB_mental", "second_deckB_boredom",
         "third_deckA_mental", "third_deckA_boredom", "third_deckB_mental", "third_deckB_boredom",
         "fourth_deckA_mental", "fourth_deckA_boredom", "fourth_deckB_mental", "fourth_deckB_boredom",
         "fifth_deckA_mental", "fifth_deckA_boredom", "fifth_deckB_mental", "fifth_deckB_boredom",
         "sixth_deckA_mental", "sixth_deckA_boredom", "sixth_deckB_mental", "sixth_deckB_boredom",
         "seventh_deckA_mental", "seventh_deckA_boredom", "seventh_deckB_mental", "seventh_deckB_boredom",
         "eigth_deckA_mental", "eigth_deckA_boredom", "eigth_deckB_mental", "eigth_deckB_boredom",
         "ninth_deckA_mental", "ninth_deckA_boredom", "ninth_deckB_mental", "ninth_deckB_boredom",
         "tenth_deckA_mental", "tenth_deckA_boredom", "tenth_deckB_mental", "tenth_deckB_boredom"], axis = 1, inplace= True)

In [21]:
df.drop(["bps_1", "bps_2", "bps_3", "bps_4", "bps_5", "bps_6", "bps_7", "bps_8",
        "moe_1", "moe_2", "moe_3", "moe_4", "moe_5", "moe_6", "moe_7", "moe_8", "moe_9",
        "moe_10", "moe_11", "moe_12", "moe_13", "moe_14", "moe_15", "moe_16", "moe_17",
         "moe_18"], axis=1, inplace=True)

In [24]:
df["attencheck1"].value_counts()

attencheck1
Green     172
Yellow     19
Name: count, dtype: int64

In [28]:
df = df.drop(df[df["attencheck1"] == "Yellow"].index)

In [29]:
df["attencheck1"].value_counts()

attencheck1
Green    172
Name: count, dtype: int64

In [30]:
df["attencheck2"].value_counts()

attencheck2
Blue     170
Green      1
           1
Name: count, dtype: int64

In [31]:
df = df.drop(df[df["attencheck2"] == "Green"].index)

In [32]:
df["attencheck2"].value_counts()

attencheck2
Blue    170
          1
Name: count, dtype: int64

In [34]:
df["selfadmit"].value_counts()

selfadmit
No     91
Yes    80
Name: count, dtype: int64

In [35]:
df = df.drop(df[df["selfadmit"] == "Yes"].index)

In [36]:
df["selfadmit"].value_counts()

selfadmit
No    91
Name: count, dtype: int64

In [37]:
df

,PID,attencheck1,q1,@1_str1,@2_str1,@3_str1,@4_str1,@5_str1,@6_str1,@7_str1,...,nfc_9,nfc_10,nfc_11,nfc_12,nfc_13,nfc_14,nfc_15,nfc_16,nfc_17,nfc_18
0,1,Green,DECK A,,,,,,,,...,4,3,2,3,3,4,2,4,5,4
1,2,Green,DECK B,blue,,,,,,green,...,2,4,4,1,4,5,4,5,1,2
2,3,Green,DECK B,,,red,yellow,,,,...,3,5,5,1,3,4,4,4,3,3
3,4,Green,DECK A,,,,,,,,...,4,2,4,3,2,3,3,4,2,2
6,7,Green,DECK B,,,,,,blue,green,...,4,5,4,1,4,4,3,5,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,187,Green,DECK B,,,,,,,green,...,5,4,5,4,5,4,5,4,5,4
187,188,Green,DECK B,,,,,,blue,,...,4,5,4,3,4,5,4,3,4,5
188,189,Green,DECK B,,,,,,blue,green,...,5,4,5,4,5,4,4,3,4,5
189,190,Green,DECK B,,,red,,blue,,,...,4,5,4,5,4,4,5,4,5,4
190,191,Green,DECK B,,,,yellow,,,,...,5,4,5,4,5,4,5,4,5,4