In [129]:
import pandas as pd

In [130]:
df = pd.read_csv("./Study1.csv")
df.columns.values

array(['PID', 'attencheck1', 'q1', 'q1ans', 'q2', 'q2ans', 'q3', 'q3ans',
       'q4', 'q4ans', 'q5', 'q5ans', 'q6', 'q6ans', 'q7', 'q7ans', 'q8',
       'q8ans', 'q9', 'q9ans', 'q10', 'q10ans', 'first_deckA_mental',
       'first_deckA_boredom', 'first_deckB_mental', 'first_deckB_boredom',
       'q11', 'q11ans', 'q12', 'q12ans', 'q13', 'q13ans', 'q14', 'q14ans',
       'q15', 'q15ans', 'q16', 'q16ans', 'q17', 'q17ans', 'q18', 'q18ans',
       'q19', 'q19ans', 'q20', 'q20ans', 'second_deckA_mental',
       'second_deckA_boredom', 'second_deckB_mental',
       'second_deckB_boredom', 'q21', 'q21ans', 'q22', 'q22ans', 'q23',
       'q23ans', 'q24', 'q24ans', 'q25', 'q25ans', 'q26', 'q26ans', 'q27',
       'q27ans', 'q28', 'q28ans', 'q29', 'q29ans', 'q30', 'q30ans',
       'third_deckA_mental', 'third_deckA_boredom', 'third_deckB_mental',
       'third_deckB_boredom', 'q31', 'q31ans', 'q32', 'q32ans', 'q33',
       'q33ans', 'q34', 'q34ans', 'q35', 'q35ans', 'q36', 'q36ans', 'q37',
       'q37ans', 'q38', 'q38ans', 'q39', 'q39ans', 'q40', 'q40ans',
       'fourth_deckA_mental', 'fourth_deckA_boredom',
       'fourth_deckB_mental', 'fourth_deckB_boredom', 'selfadmit',
       'attencheck2', 'nfc_1r', 'nfc_2r', 'nfc_3r', 'nfc_4r', 'nfc_5r',
       'nfc_6r', 'nfc_7r', 'nfc_8r', 'nfc_9r', 'nfc_10r', 'nfc_11r',
       'nfc_12r', 'nfc_13r', 'nfc_14r', 'nfc_15r', 'nfc_16r', 'nfc_17r',
       'nfc_18r', 'bps_1r', 'bps_2r', 'bps_3r', 'bps_4r', 'bps_5r',
       'bps_6r', 'bps_7r', 'bps_8r', 'moe_1r', 'moe_2r', 'moe_3r',
       'moe_4r', 'moe_5r', 'moe_6r', 'moe_7r', 'moe_8r', 'moe_9r',
       'moe_10r', 'moe_11r', 'moe_12r', 'moe_13r', 'moe_14r', 'moe_15r',
       'moe_16r', 'moe_17r', 'moe_18r'], dtype=object)

In [132]:
df.drop(["first_deckA_mental", "first_deckA_boredom", "first_deckB_mental", "first_deckB_boredom",
         "second_deckA_mental", "second_deckA_boredom", "second_deckB_mental", "second_deckB_boredom",
          "third_deckA_mental", "third_deckA_boredom", "third_deckB_mental", "third_deckB_boredom",
           "fourth_deckA_mental", "fourth_deckA_boredom", "fourth_deckB_mental", "fourth_deckB_boredom"],
           axis=1, inplace=True)

Tagit bort alla checkar mellan fr√•gorna

In [133]:
df.columns.values

array(['PID', 'attencheck1', 'q1', 'q1ans', 'q2', 'q2ans', 'q3', 'q3ans',
       'q4', 'q4ans', 'q5', 'q5ans', 'q6', 'q6ans', 'q7', 'q7ans', 'q8',
       'q8ans', 'q9', 'q9ans', 'q10', 'q10ans', 'q11', 'q11ans', 'q12',
       'q12ans', 'q13', 'q13ans', 'q14', 'q14ans', 'q15', 'q15ans', 'q16',
       'q16ans', 'q17', 'q17ans', 'q18', 'q18ans', 'q19', 'q19ans', 'q20',
       'q20ans', 'q21', 'q21ans', 'q22', 'q22ans', 'q23', 'q23ans', 'q24',
       'q24ans', 'q25', 'q25ans', 'q26', 'q26ans', 'q27', 'q27ans', 'q28',
       'q28ans', 'q29', 'q29ans', 'q30', 'q30ans', 'q31', 'q31ans', 'q32',
       'q32ans', 'q33', 'q33ans', 'q34', 'q34ans', 'q35', 'q35ans', 'q36',
       'q36ans', 'q37', 'q37ans', 'q38', 'q38ans', 'q39', 'q39ans', 'q40',
       'q40ans', 'selfadmit', 'attencheck2', 'nfc_1r', 'nfc_2r', 'nfc_3r',
       'nfc_4r', 'nfc_5r', 'nfc_6r', 'nfc_7r', 'nfc_8r', 'nfc_9r',
       'nfc_10r', 'nfc_11r', 'nfc_12r', 'nfc_13r', 'nfc_14r', 'nfc_15r',
       'nfc_16r', 'nfc_17r', 'nfc_18r', 'bps_1r', 'bps_2r', 'bps_3r',
       'bps_4r', 'bps_5r', 'bps_6r', 'bps_7r', 'bps_8r', 'moe_1r',
       'moe_2r', 'moe_3r', 'moe_4r', 'moe_5r', 'moe_6r', 'moe_7r',
       'moe_8r', 'moe_9r', 'moe_10r', 'moe_11r', 'moe_12r', 'moe_13r',
       'moe_14r', 'moe_15r', 'moe_16r', 'moe_17r', 'moe_18r'],
      dtype=object)

In [134]:
df.drop(["bps_1r", "bps_2r", "bps_3r", "bps_4r", "bps_5r", "bps_6r", "bps_7r", "bps_8r",
         "moe_1r", "moe_2r", "moe_3r", "moe_4r", "moe_5r", "moe_6r", "moe_7r", 
         "moe_8r", "moe_9r", "moe_10r", "moe_11r", "moe_12r", "moe_13r", "moe_14r",
         "moe_15r", "moe_16r", "moe_17r", "moe_18r"], axis=1, inplace=True)

In [135]:
df.columns.values

array(['PID', 'attencheck1', 'q1', 'q1ans', 'q2', 'q2ans', 'q3', 'q3ans',
       'q4', 'q4ans', 'q5', 'q5ans', 'q6', 'q6ans', 'q7', 'q7ans', 'q8',
       'q8ans', 'q9', 'q9ans', 'q10', 'q10ans', 'q11', 'q11ans', 'q12',
       'q12ans', 'q13', 'q13ans', 'q14', 'q14ans', 'q15', 'q15ans', 'q16',
       'q16ans', 'q17', 'q17ans', 'q18', 'q18ans', 'q19', 'q19ans', 'q20',
       'q20ans', 'q21', 'q21ans', 'q22', 'q22ans', 'q23', 'q23ans', 'q24',
       'q24ans', 'q25', 'q25ans', 'q26', 'q26ans', 'q27', 'q27ans', 'q28',
       'q28ans', 'q29', 'q29ans', 'q30', 'q30ans', 'q31', 'q31ans', 'q32',
       'q32ans', 'q33', 'q33ans', 'q34', 'q34ans', 'q35', 'q35ans', 'q36',
       'q36ans', 'q37', 'q37ans', 'q38', 'q38ans', 'q39', 'q39ans', 'q40',
       'q40ans', 'selfadmit', 'attencheck2', 'nfc_1r', 'nfc_2r', 'nfc_3r',
       'nfc_4r', 'nfc_5r', 'nfc_6r', 'nfc_7r', 'nfc_8r', 'nfc_9r',
       'nfc_10r', 'nfc_11r', 'nfc_12r', 'nfc_13r', 'nfc_14r', 'nfc_15r',
       'nfc_16r', 'nfc_17r', 'nfc_18r'], dtype=object)

In [136]:
df["attencheck1"].value_counts()

attencheck1
Green     129
Yellow     15
Name: count, dtype: int64

In [137]:
df = df.drop(df[df["attencheck1"] == "Yellow"].index)

df["attencheck1"].value_counts()

attencheck1
Green    129
Name: count, dtype: int64

In [138]:
df["attencheck2"].value_counts()

attencheck2
Blue     128
Green      1
Name: count, dtype: int64

In [139]:
df = df.drop(df[df["attencheck2"] == "Green"].index)

In [140]:
df["attencheck2"].value_counts()

attencheck2
Blue    128
Name: count, dtype: int64

In [141]:
df["selfadmit"].value_counts()

selfadmit
No     81
Yes    47
Name: count, dtype: int64

In [142]:
df = df.drop(df[df["selfadmit"] == "Yes"].index)

In [143]:
df["selfadmit"].value_counts()

selfadmit
No    81
Name: count, dtype: int64

In [144]:
df.columns.values

array(['PID', 'attencheck1', 'q1', 'q1ans', 'q2', 'q2ans', 'q3', 'q3ans',
       'q4', 'q4ans', 'q5', 'q5ans', 'q6', 'q6ans', 'q7', 'q7ans', 'q8',
       'q8ans', 'q9', 'q9ans', 'q10', 'q10ans', 'q11', 'q11ans', 'q12',
       'q12ans', 'q13', 'q13ans', 'q14', 'q14ans', 'q15', 'q15ans', 'q16',
       'q16ans', 'q17', 'q17ans', 'q18', 'q18ans', 'q19', 'q19ans', 'q20',
       'q20ans', 'q21', 'q21ans', 'q22', 'q22ans', 'q23', 'q23ans', 'q24',
       'q24ans', 'q25', 'q25ans', 'q26', 'q26ans', 'q27', 'q27ans', 'q28',
       'q28ans', 'q29', 'q29ans', 'q30', 'q30ans', 'q31', 'q31ans', 'q32',
       'q32ans', 'q33', 'q33ans', 'q34', 'q34ans', 'q35', 'q35ans', 'q36',
       'q36ans', 'q37', 'q37ans', 'q38', 'q38ans', 'q39', 'q39ans', 'q40',
       'q40ans', 'selfadmit', 'attencheck2', 'nfc_1r', 'nfc_2r', 'nfc_3r',
       'nfc_4r', 'nfc_5r', 'nfc_6r', 'nfc_7r', 'nfc_8r', 'nfc_9r',
       'nfc_10r', 'nfc_11r', 'nfc_12r', 'nfc_13r', 'nfc_14r', 'nfc_15r',
       'nfc_16r', 'nfc_17r', 'nfc_18r'], dtype=object)

In [145]:
df2 = pd.read_csv("./Study1.csv")

In [146]:
df

,PID,attencheck1,q1,q1ans,q2,q2ans,q3,q3ans,q4,q4ans,...,nfc_9r,nfc_10r,nfc_11r,nfc_12r,nfc_13r,nfc_14r,nfc_15r,nfc_16r,nfc_17r,nfc_18r
1,2,Green,ADD 3,correct,ADD 3,correct,DO NOTHING,,ADD 3,incorrect,...,3,3,4,3,3,3,3,5,2,5
6,7,Green,DO NOTHING,,ADD 3,incorrect,DO NOTHING,,DO NOTHING,,...,3,3,3,4,2,2,2,4,2,3
7,8,Green,ADD 3,correct,ADD 3,correct,ADD 3,correct,ADD 3,incorrect,...,2,4,4,2,3,4,4,3,3,4
8,9,Green,ADD 3,correct,DO NOTHING,,ADD 3,correct,ADD 3,correct,...,1,4,5,1,5,4,5,5,2,4
9,10,Green,ADD 3,incorrect,ADD 3,incorrect,DO NOTHING,,ADD 3,incorrect,...,4,4,4,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,134,Green,ADD 3,incorrect,DO NOTHING,,ADD 3,incorrect,ADD 3,incorrect,...,4,4,3,2,4,1,3,3,2,4
137,138,Green,DO NOTHING,,ADD 3,incorrect,DO NOTHING,,ADD 3,incorrect,...,4,4,3,4,1,1,1,3,2,2
139,140,Green,ADD 3,incorrect,DO NOTHING,,ADD 3,correct,ADD 3,correct,...,4,4,3,2,4,4,5,4,4,3
140,141,Green,DO NOTHING,,ADD 3,incorrect,DO NOTHING,,ADD 3,incorrect,...,4,2,3,3,1,1,2,4,4,3
142,143,Green,ADD 3,correct,DO NOTHING,,ADD 3,correct,ADD 3,correct,...,5,3,2,4,1,3,2,2,5,2

In [147]:
df2

,PID,attencheck1,q1,q1ans,q2,q2ans,q3,q3ans,q4,q4ans,...,moe_9r,moe_10r,moe_11r,moe_12r,moe_13r,moe_14r,moe_15r,moe_16r,moe_17r,moe_18r
0,1,Green,ADD 3,incorrect,DO NOTHING,,ADD 3,correct,ADD 3,correct,...,5,3,3,4,3,4,4,4,3,3
1,2,Green,ADD 3,correct,ADD 3,correct,DO NOTHING,,ADD 3,incorrect,...,3,1,3,5,4,4,3,3,4,3
2,3,Yellow,DO NOTHING,,ADD 3,incorrect,DO NOTHING,,ADD 3,correct,...,4,4,3,3,5,3,3,3,1,3
3,4,Green,ADD 3,correct,ADD 3,correct,ADD 3,correct,DO NOTHING,,...,4,5,1,1,3,4,5,5,5,5
4,5,Green,DO NOTHING,,DO NOTHING,,ADD 3,correct,ADD 3,incorrect,...,4,5,5,5,3,4,4,4,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,140,Green,ADD 3,incorrect,DO NOTHING,,ADD 3,correct,ADD 3,correct,...,4,3,4,5,4,4,3,3,1,3
140,141,Green,DO NOTHING,,ADD 3,incorrect,DO NOTHING,,ADD 3,incorrect,...,5,1,5,5,5,5,4,4,3,3
141,142,Green,DO NOTHING,,ADD 3,incorrect,DO NOTHING,,DO NOTHING,,...,4,3,4,3,3,4,4,4,1,3
142,143,Green,ADD 3,correct,DO NOTHING,,ADD 3,correct,ADD 3,correct,...,5,3,4,5,3,5,3,4,1,4
143,144,Green,DO NOTHING,,ADD 3,correct,ADD 3,correct,ADD 3,correct,...,5,1,3,5,3,4,5,4,3,3